version: '3'
services:
  apache:
    image: httpd
    container_name: apache_test1
    volumes:
      - ./src:/var/www/html
    labels:
      - "traefik.http.routers.apache.rule=Host(`web.site.localhost`)"
      - "traefik.http.services.apache.loadbalancer.server.port=80"
db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_test2
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.site.localhost`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
traefik:
    image: traefik:v2.3
    command:
      - --log.level=INFO
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "80:80"
